@extends('layouts.app')
@section('content')
@php
$school=\App\Support\School::class;
@endphp
<div class="welcome"><div><h2>{{ __('Selamat pagi, Admin Sekolah') }}</h2><p class="muted">{{ now()->locale(session('locale','id'))->translatedFormat('l, j F Y') }}</p></div><div class="actions"><a class="btn secondary" href="/admin/kelas">{{ __('Tahun ajaran 2026/27') }}</a><a class="btn" href="/admin/laporan">{{ __('Unduh laporan') }}</a></div></div>
<x-stats :items="[[$school::metric('students',360,4),'Siswa aktif','users'],[$school::metric('staff',28,4),'Guru & staf','briefcase'],[$school::metric('applicants',68,4),'Pendaftar PPDB','file'],[12,'Menunggu daftar ulang','calendar']]"/>
<div class="actions"><a class="btn secondary" href="/admin/pendaftar">{{ __('Periksa pendaftar') }}</a><a class="btn secondary" href="/admin/daftar-ulang">{{ __('Daftar ulang offline') }}</a><a class="btn secondary" href="/admin/website">{{ __('Kelola website') }}</a><a class="btn secondary" href="/admin/siswa">{{ __('Lihat siswa') }}</a></div>
<div class="grid-2"><x-card title="Progres PPDB 2027/2028"><div class="progress-flex"><div class="donut"><div><strong>{{ $school::metric('applicants',68,4) }}</strong><small>{{ __('Pendaftar') }}</small></div></div><div class="progress-legend">@foreach([['Sedang diperiksa',14],['Perlu perbaikan',8],['Menunggu daftar ulang',12],['Tahap lain',34]] as [$label,$count])<div><span>{{ __($label) }}</span><strong>{{ $count }}</strong></div>@endforeach</div></div><a class="card-link" href="/admin/pendaftar">{{ __('Lihat pendaftar') }}</a></x-card>
<x-card title="Perlu ditindaklanjuti">@foreach([['14 pendaftar belum diperiksa','Periksa data anak, wali, dan berkas','pendaftar'],['12 daftar ulang belum selesai','Lengkapi dokumen asli dan pembayaran','daftar-ulang'],['2 draf website menunggu tinjauan','Periksa sebelum publikasi','publikasi']] as [$name,$desc,$link])<a href="/admin/{{ $link }}" class="detail-line"><x-icon name="file"/><div><strong>{{ __($name) }}</strong><small>{{ __($desc) }}</small></div></a>@endforeach</x-card></div>
<div class="grid-3"><x-card title="Kehadiran siswa hari ini"><div class="big-number">96,1%</div><p class="muted">{{ __('346 dari 360 siswa hadir') }}</p><div class="attendance-bar"></div>@foreach([['Hadir',346],['Izin / sakit',9],['Alpa',5]] as [$label,$count])<div class="detail-line"><x-icon name="file"/><div><strong>{{ __($label) }}</strong><small>{{ $count }}</small></div></div>@endforeach<a class="card-link" href="/admin/absensi">{{ __('Lihat absensi') }}</a></x-card>
<x-card title="Website sekolah"><img src="/assets/classroom.jpeg" class="classroom-thumb" alt="Ruang belajar SD Ceria Nusantara"><x-badge value="Terbit"/><p style="margin:16px 0;font-weight:500">Belajar Ceria, Tumbuh Percaya Diri</p><a class="card-link" href="/admin/website">{{ __('Kelola website') }}</a></x-card>
<x-card title="Pengumuman & agenda">@foreach([['Pekan Literasi Ceria','8–12 Oktober · Semua kelas'],['Pertemuan orang tua','17 Oktober · Aula sekolah'],['PPDB dibuka','Oktober 2026–Mei 2027']] as [$label,$date])<a href="/admin/agenda" class="detail-line"><x-icon name="file"/><div><strong>{{ __($label) }}</strong><small>{{ __($date) }}</small></div></a>@endforeach</x-card></div>
<x-card title="Ringkasan keuangan"><div class="money-summary"><div><p>{{ __('Tagihan SPP Oktober') }}</p><strong>Rp108 jt</strong></div><div><p>{{ __('Pembayaran terkonfirmasi') }}</p><strong>Rp81 jt</strong></div><div><p>{{ __('Sisa tagihan') }}</p><strong>Rp27 jt</strong></div></div><a href="/admin/pembayaran" class="card-link">{{ __('Lihat pembayaran') }}</a></x-card><footer class="footer">© 2026 SD Ceria Nusantara · {{ __('Administrasi sekolah & website') }}</footer>
@endsection
