@extends('layouts.app')
@section('content')
@php
$active=request('tab','verifikasi');
$invoices=\App\Models\SchoolRecord::ofKind('invoices')->get();
if(request('student'))$invoices=$invoices->filter(fn($r)=>(string)$r->value('student_id')===request('student'));
$invoice=$invoices->firstWhere('id',(int)request('invoice'))??$invoices->first();
$d=$invoice?\App\Support\School::invoice($invoice):null;
$payments=$invoice?\Illuminate\Support\Facades\DB::table('school_payments')->where('invoice_id',$invoice->id)->orderByDesc('id')->get():collect();
@endphp
<div class="tabs">@foreach(['verifikasi'=>'Verifikasi','tunai'=>'Tunai di sekolah','riwayat'=>'Riwayat','kuitansi'=>'Kuitansi'] as $key=>$label)<a class="{{ $active===$key?'active':'' }}" href="?tab={{ $key }}&invoice={{ $invoice?->id }}">{{ $label }}</a>@endforeach</div>
<x-card title="Cari tagihan siswa"><form method="get" class="form-grid no-margin"><input type="hidden" name="tab" value="{{ $active }}"><label class="field">Nama / nomor induk<select name="invoice" data-auto-submit>@foreach($invoices as $item)<option value="{{ $item->id }}" @selected($invoice?->id===$item->id)>{{ $item->value('name') }}</option>@endforeach</select></label><label class="field">Tahun / periode<input value="2026/2027 · {{ $d['period']??'—' }}" readonly></label></form></x-card>
@if($invoice)<x-card :title="$d['name']"><div class="money-summary"><div><p>Tagihan</p><strong>{{ \App\Support\School::money($d['amount']) }}</strong></div><div><p>Dibayar</p><strong>{{ \App\Support\School::money($d['paid']) }}</strong></div><div><p>Sisa</p><strong>{{ \App\Support\School::money($d['balance']) }}</strong></div></div></x-card>
@if($active==='tunai')<x-card title="Catat Pembayaran Tunai"><form action="/admin/pembayaran/catat" method="post" data-confirm="Simpan pembayaran tunai ini? Nominal akan langsung mengurangi sisa tagihan.">@csrf<input type="hidden" name="invoice_id" value="{{ $invoice->id }}"><input type="hidden" name="method" value="Tunai di sekolah"><div class="form-grid"><label class="field">Nominal diterima<input type="number" name="amount" min="1" max="{{ $d['balance'] }}" value="{{ old('amount',$d['balance']) }}" required></label><label class="field">Tanggal penerimaan<input type="date" name="received_at" value="{{ old('received_at',now()->toDateString()) }}" required></label><label class="field">Referensi / nomor kuitansi<input name="reference" value="{{ old('reference','KW-SPP-'.now()->format('YmdHis')) }}" required></label><label class="field">Petugas penerima<input value="{{ auth()->user()->name }}" readonly></label></div><div class="actions"><button class="btn" @disabled($d['balance']===0)>Simpan perubahan</button><a href="/admin/pembayaran" class="btn secondary">Batal</a></div></form></x-card>
@else<div class="table-wrap"><table><thead><tr><th>Referensi</th><th>Metode</th><th>Nominal</th><th>Tanggal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($payments->filter(fn($p)=>$active!=='kuitansi'||$p->status==='Terverifikasi') as $payment)<tr><td>{{ $payment->reference }}</td><td>{{ $payment->method }}</td><td>{{ \App\Support\School::money($payment->amount) }}</td><td>{{ \App\Support\School::date($payment->received_at) }}</td><td><x-badge :value="$payment->status"/></td><td>@if($payment->status==='Menunggu')<form method="post" action="/admin/pembayaran/{{ $payment->id }}/verify" data-confirm="Pastikan nominal dan referensi sesuai mutasi rekening sebelum memverifikasi pembayaran.">@csrf<button class="btn small secondary">Verifikasi</button></form>@else<a href="/admin/kuitansi/{{ $payment->id }}">Lihat kuitansi</a>@endif</td></tr>@empty<tr><td colspan="6"><div class="empty">Belum ada pembayaran.</div></td></tr>@endforelse</tbody></table></div><x-notice>SPP: virtual account / QR dapat dikonfirmasi otomatis setelah integrasi penyedia pembayaran; transfer manual diperiksa petugas; tunai dicatat di sekolah.</x-notice><div class="actions"><a href="?tab=tunai&invoice={{ $invoice->id }}" class="btn">Catat pembayaran tunai</a><a href="?tab=kuitansi&invoice={{ $invoice->id }}" class="btn secondary">Lihat kuitansi</a></div>@endif
@else<div class="empty">Belum ada tagihan siswa.</div>@endif
@endsection
