@extends('layouts.app')
@section('content')
@php
$student=$kind==='students'; $d=$record->data;
$tabs=$student?['detail'=>['Detail siswa','users'],'kehadiran'=>['Kehadiran','calendar'],'tagihan'=>['SPP & tagihan','wallet'],'nilai'=>['Nilai & rapor','book'],'dokumen'=>['Dokumen','file']]:['detail'=>['Detail profil','users'],'jadwal'=>['Jadwal mengajar','calendar'],'kehadiran'=>['Kehadiran','wallet'],'cuti'=>['Cuti','book'],'dokumen'=>['Dokumen','file']];
if(!$student && $record->value('position')==='Tata Usaha') unset($tabs['jadwal']);
$info=$student?['Kelas / tahun ajaran'=>($d['class']??'').' · '.($d['year']??''),'Nomor induk siswa'=>$record->code,'Jenis kelamin'=>$d['gender']??'','Tanggal lahir'=>\App\Support\School::date($d['birth_date']??''),'Wali kelas'=>'Siti Rahma, S.Pd.','Orang tua / wali'=>$d['guardian']??'','Telepon wali'=>$d['phone']??'','Email wali'=>$d['email']??'']:['Penugasan'=>$d['assignment']??'','Status kepegawaian'=>($d['position']??'')==='Tata Usaha'?'Staf tetap':'Guru tetap','Tanggal bergabung'=>\App\Support\School::date($d['joined']??''),'Pendidikan terakhir'=>$d['education']??'','Jenis kelamin'=>$d['gender']??'','Tanggal lahir'=>\App\Support\School::date($d['birth_date']??''),'Telepon'=>$d['phone']??'','Email'=>$d['email']??''];
$documents=\Illuminate\Support\Facades\DB::table('school_documents')->whereIn('record_id',array_filter([$record->id,$record->value('applicant_id')]))->get();
@endphp
<section class="profile-card"><div class="profile-identity"><img class="profile-avatar" src="/assets/{{ $student?'student.png':($record->value('position')==='Tata Usaha'?'staff.png':'teacher.png') }}" alt="Ilustrasi profil {{ $d['name'] }}"><h2>{{ $d['name'] }}</h2><a href="/admin/identitas/{{ $record->id }}">{{ $student?'NIS:':'ID:' }} {{ $record->code }}</a><p>{{ $student?'Kelas '.$d['class'].' · No. absen 03':($d['assignment']??'').' · '.($d['position']??'') }}</p><div class="actions"><a class="btn secondary" href="/admin/identitas/{{ $record->id }}" target="_blank">Kartu identitas</a><a class="btn" href="/admin/{{ $screen }}/{{ $record->id }}/edit">Edit profil</a></div></div><div class="profile-info"><div class="card-heading"><h3>Informasi pribadi</h3><x-badge :value="$record->value('status')"/></div><dl class="definition">@foreach($info as $key=>$value)<dt>{{ $key }}</dt><dd>{{ $value ?: '—' }}</dd>@endforeach</dl></div></section>
<div class="tabs" aria-label="Detail profil">@foreach($tabs as $key=>[$label,$icon])<a class="{{ $tab===$key?'active':'' }}" href="/admin/{{ $screen }}/{{ $record->id }}/{{ $key }}"><x-icon :name="$icon"/>{{ $label }}</a>@endforeach</div>
@if($tab==='detail')
@if($student)<x-card title="Orang tua & wali">@foreach([[$d['father']??'','Ayah','DP'],[$d['guardian']??'','Ibu / Wali utama','RP']] as [$name,$relation,$initials])@if($name)<div class="guardian"><span class="avatar">{{ $initials }}</span><div><strong>{{ $name }}</strong><small>{{ $relation }}</small><small>{{ $d['phone']??'' }} · {{ $d['email']??'' }}</small></div><x-badge value="Terhubung"/></div>@endif @endforeach</x-card>
@else<x-card title="Detail profil"><div class="inline-def">@foreach(['Pendidikan'=>$d['education']??'','Pengalaman di sekolah'=>'7 tahun','Penugasan'=>$d['assignment']??'','Status'=>$d['status']??''] as $key=>$value)<div><p>{{ $key }}</p><span>{{ $value }}</span></div>@endforeach</div></x-card>@endif
<div class="grid-2"><x-card :title="$student?'Alamat & keluarga':'Alamat & kontak darurat'"><p class="muted">{{ $d['address']??'Jl. Pelangi Imajiner No. 20, Kota Imajinaria' }}</p><dl class="definition"><dt>Kontak darurat</dt><dd>{{ $d['guardian']??'Keluarga' }} · {{ $d['phone']??'—' }}</dd>@if($student)<dt>Alamat domisili</dt><dd>Sama dengan alamat keluarga</dd>@endif</dl></x-card>
<x-card :title="$student?'Riwayat sekolah':(($d['position']??'')==='Tata Usaha'?'Tugas & tanggung jawab':'Kelas & mata pelajaran')">@if($student)<dl class="definition"><dt>Sekolah sebelumnya</dt><dd>{{ $d['previous_school']??'—' }}</dd><dt>Tahun masuk</dt><dd>{{ $d['year'] }}</dd><dt>Tanggal aktif</dt><dd>{{ \App\Support\School::date($d['joined']??'2026-07-15') }}</dd><dt>Status siswa</dt><dd>Aktif</dd></dl>@else<div class="detail-line"><x-icon name="file"/><div><strong>{{ $d['assignment']??'' }}</strong><small>{{ $d['position']??'' }} · Tahun 2026/2027</small></div></div><div class="detail-line"><x-icon name="file"/><div><strong>{{ ($d['position']??'')==='Tata Usaha'?'Pemeriksaan PPDB':'Literasi & numerasi' }}</strong><small>Senin–Jumat · Tahun 2026/2027</small></div></div>@endif</x-card></div>
<x-card :title="$student?'Dokumen siswa':'Dokumen kepegawaian'">@include('admin.documents',['compact'=>true])<a href="/admin/{{ $screen }}/{{ $record->id }}/dokumen">Lihat semua dokumen</a></x-card>
@if($student)<x-card title="Dukungan belajar"><p class="muted">Catatan wali kelas dan informasi penting yang disampaikan keluarga.</p><dl class="definition"><dt>Kontak pendamping</dt><dd>Siti Rahma · Wali kelas</dd><dt>Catatan kebutuhan</dt><dd>{{ $d['support_notes']??'Tidak ada catatan tambahan' }}</dd></dl><small class="muted">Catatan sensitif hanya ditampilkan kepada petugas berwenang.</small></x-card>@endif
@elseif($tab==='kehadiran')
@if($student)<x-stats :items="[['96%','Kehadiran bulan ini','chart'],['24 hari','Hadir','calendar'],['1 hari','Izin / sakit','file']]"/>@else<x-stats :items="[['21 hari','Hadir bulan ini','calendar'],['1 hari','Izin / sakit','file'],[0,'Keterlambatan','clock']]"/>@endif
@php
$attendance=\App\Models\SchoolRecord::ofKind('attendance')->where('data->student_id',$record->id)->get()->map(fn($r)=>$r->data);
@endphp
<x-table :columns="['date'=>'Tanggal','name'=>'Nama','notes'=>'Keterangan','author'=>'Dicatat oleh','status'=>'Kehadiran']" :rows="$attendance"/>
@elseif($tab==='tagihan')
@php
$invoices=\App\Models\SchoolRecord::ofKind('invoices')->where('data->student_id',$record->id)->get()->map(fn($r)=>[...\App\Support\School::invoice($r),'_url'=>'/admin/pembayaran?invoice='.$r->id]);
@endphp
<x-stats :items="[[\App\Support\School::money($invoices->sum('amount')),'Total tagihan','wallet'],[\App\Support\School::money($invoices->sum('paid')),'Telah dibayar','wallet'],[\App\Support\School::money($invoices->sum('balance')),'Sisa tagihan','file']]"/>
<x-table :columns="['name'=>'Tagihan','due_date'=>'Jatuh tempo','amount'=>'Nominal','balance'=>'Sisa','status'=>'Status']" :rows="$invoices"/><div class="actions"><a class="btn secondary" href="/admin/pembayaran?student={{ $record->id }}">Lihat pembayaran</a><a class="btn secondary" href="/admin/pembayaran?tab=kuitansi&student={{ $record->id }}">Lihat kuitansi</a></div><x-notice>Tagihan SPP terpisah dari biaya daftar ulang calon siswa.</x-notice>
@elseif($tab==='nilai')
@php
$grades=\App\Models\SchoolRecord::ofKind('grades')->where('data->student_id',$record->id)->get();
@endphp
<x-table :columns="['subject'=>'Mata pelajaran','semester'=>'Semester','score'=>'Nilai','author'=>'Guru','status'=>'Status']" :rows="$grades->map(fn($r)=>$r->data)"/><x-card title="Perkembangan & catatan wali kelas"><p class="muted">{{ $grades->first()?->value('notes') ?? 'Belum ada catatan perkembangan.' }}</p></x-card><button class="btn secondary no-print" data-print>Cetak / Simpan rapor PDF</button>
@elseif($tab==='jadwal')
<x-table :columns="['day'=>'Hari','time'=>'Waktu','subject'=>'Pelajaran','class'=>'Kelas / ruang','status'=>'Status']" :rows="[['day'=>'Senin','time'=>'07.30–09.00','subject'=>'Literasi & numerasi','class'=>$d['assignment'],'status'=>'Aktif'],['day'=>'Selasa','time'=>'07.30–09.00','subject'=>'Bahasa Indonesia','class'=>$d['assignment'],'status'=>'Aktif'],['day'=>'Rabu','time'=>'09.30–10.30','subject'=>'Seni & kreativitas','class'=>$d['assignment'],'status'=>'Aktif']]"/>
@elseif($tab==='cuti')<x-notice>Tinjau pengajuan cuti sesuai kewenangan petugas.</x-notice><x-table :columns="['period'=>'Periode','type'=>'Jenis','reason'=>'Alasan','reviewer'=>'Peninjau','status'=>'Status']" :rows="[['period'=>'7–8 Okt 2026','type'=>'Izin pribadi','reason'=>'Urusan keluarga','reviewer'=>'Admin Sekolah','status'=>'Menunggu'],['period'=>'4 Agu 2026','type'=>'Sakit','reason'=>'Surat keterangan','reviewer'=>'Admin Sekolah','status'=>'Selesai']]"/>
@elseif($tab==='dokumen')<x-card title="Berkas & identitas">@include('admin.documents',['compact'=>false])<div class="doc-row"><x-icon name="file"/><div>Kartu identitas {{ $student?'siswa':'guru / staf' }}<small>Cetak atau simpan sebagai PDF</small></div><a href="/admin/identitas/{{ $record->id }}" target="_blank" aria-label="Cetak kartu identitas"><x-icon name="download"/></a></div></x-card><x-card title="Unggah dokumen"><form method="post" enctype="multipart/form-data" action="/admin/dokumen/{{ $record->id }}">@csrf<div class="form-grid"><label class="field">Nama dokumen<input name="name" required placeholder="Contoh: Akta kelahiran"></label><label class="field">Berkas PDF / JPG / PNG · Maks. 5 MB<input type="file" name="document" accept=".pdf,.jpg,.jpeg,.png" required></label></div><button class="btn">Unggah dokumen</button></form></x-card>
@else<div class="empty">Tab tidak ditemukan.</div>@endif
@endsection
