@extends('layouts.app')
@section('content')
@include('website.toolbar')
@php
$contents=\App\Models\SchoolRecord::ofKind('content')->get();
$rows=$contents->map(fn($r)=>['name'=>$r->value('name'),'summary'=>$r->value('summary'),'date'=>$r->value('date'),'status'=>$r->value('status'),'_url'=>'/admin/website/'.$r->value('section').'/edit']);
$hero=\App\Support\School::content()['hero'];
@endphp
@if($screen==='website')
<x-stats :items="[[8,'Halaman terbit','globe'],[$contents->where('data.status','Draf')->count(),'Draf untuk ditinjau','file'],[\App\Support\School::metric('applicants',68,4),'Pendaftar online','users']]"/>
<div class="split-wide"><x-card title="Landing page sekolah"><img class="cover-image" src="/assets/{{ $hero['image'] }}" alt="Ruang belajar SD Ceria Nusantara"><h1>{{ $hero['title'] }}</h1><p class="muted" style="margin:16px 0">{{ $hero['description'] }}</p><x-badge value="Terbit"/><div class="actions" style="margin-top:16px"><a class="btn" href="/admin/website/hero/edit">Edit landing page</a></div></x-card><x-card title="Informasi publik">@foreach(['Siswa aktif'=>'360+','Guru & staf'=>'28','Tahun berdiri'=>'2014','Akreditasi'=>'A'] as $key=>$value)<p class="muted">{{ $key }}</p><div class="big-number" style="font-size:24px">{{ $value }}</div>@endforeach<small class="muted">Informasi yang ditampilkan pada website sekolah.</small></x-card></div><x-card title="Bagian website"><x-table :columns="['name'=>'Bagian','summary'=>'Isi','date'=>'Diperbarui','status'=>'Status']" :rows="$rows->take(5)"/></x-card>
@elseif($screen==='halaman')<x-table :columns="['name'=>'Bagian website','summary'=>'Isi utama','date'=>'Terakhir diperbarui','status'=>'Status']" :rows="$rows->push(['name'=>'Berita & Galeri','summary'=>'Kegiatan dan informasi sekolah','date'=>'2026-10-04','status'=>'Terbit','_url'=>'/admin/berita'])"/><x-notice>Pilih bagian untuk mengubah isi. Konten diperiksa lewat pratinjau sebelum diterbitkan.</x-notice><div class="actions"><a href="/admin/media" class="btn secondary">Kelola media</a><a href="/admin/publikasi" class="btn">Tinjau draf</a></div>
@elseif($screen==='publikasi')
<x-table :columns="['name'=>'Bagian','summary'=>'Perubahan draf','author'=>'Editor','status'=>'Status']" :rows="$contents->filter(fn($r)=>$r->value('status')==='Draf')->map(fn($r)=>[...$r->data,'_url'=>'/admin/website/'.$r->value('section').'/edit'])"/>
<form method="post" action="/admin/website/publish" data-confirm="Terbitkan seluruh draf yang telah diperiksa ke website sekolah?">@csrf<x-card title="Checklist publikasi">@foreach(['text'=>'Judul dan teks sudah diperiksa','image'=>'Gambar serta teks alternatif lengkap','contact'=>'Kontak sekolah sesuai data landing page','period'=>'Periode & biaya PPDB sesuai pengaturan','offline'=>'Alur daftar ulang offline sudah jelas'] as $key=>$label)<label class="check-row"><input type="checkbox" name="checks[]" value="{{ $key }}" required>{{ $label }}</label>@endforeach<label class="field" style="margin-top:24px">Catatan publikasi<textarea name="notes" rows="3" required>Pembaruan informasi sekolah dan alur PPDB.</textarea></label></x-card><x-notice>Tinjau perubahan dan pratinjau sebelum menerbitkan. Publikasi tersedia bagi Admin dengan izin website.</x-notice><div class="actions"><a class="btn secondary" href="/admin/website/preview">Pratinjau website</a><button class="btn">Terbitkan perubahan</button><a href="/admin/halaman" class="btn white">Kembali ke draf</a></div></form>
@elseif($screen==='media')
<form class="filters" method="get"><label class="search-field"><x-icon name="search"/><input name="q" value="{{ request('q') }}" placeholder="Cari nama berkas..." aria-label="Cari nama berkas"></label><button class="btn secondary">Cari media</button><a href="#upload" class="btn">Unggah media</a></form>
@php
$media=collect([['name'=>'Logo sekolah','image'=>'logo.png','alt'=>'Logo asli dari desain sebelumnya.'],['name'=>'Ruang kelas','image'=>'classroom.jpeg','alt'=>'Hero dan pratinjau landing page.'],['name'=>'Potret pendidik','image'=>'teacher.png','alt'=>'Foto ilustratif dari desain.']])->concat(\App\Models\SchoolRecord::ofKind('media')->get()->map(fn($r)=>$r->data))->filter(fn($m)=>!request('q')||str_contains(mb_strtolower($m['name']),mb_strtolower(request('q'))));
@endphp
<div class="media-grid">@foreach($media as $item)<div class="media-tile"><img src="/assets/{{ $item['image'] }}" alt="{{ $item['alt'] }}"><h3>{{ $item['name'] }}</h3><p>{{ $item['alt'] }}</p><code>{{ $item['image'] }}</code><p><a href="/assets/{{ $item['image'] }}" download>Unduh media</a></p></div>@endforeach</div><x-card title="Unggah media" id="upload" style="margin-top:24px"><form method="post" action="/admin/website/media" enctype="multipart/form-data">@csrf<div class="form-grid"><label class="field">Gambar JPG / PNG / WebP · Maks. 5 MB<input type="file" name="image" accept=".jpg,.jpeg,.png,.webp" required></label><label class="field">Teks alternatif<input name="alt" required placeholder="Deskripsikan isi gambar"></label></div><button class="btn">Unggah media</button></form></x-card>
@elseif($screen==='terbit')<x-card class="success-state"><h2>Website berhasil diperbarui</h2><x-badge value="Terbit"/><p>Perubahan telah diterbitkan. Riwayat publikasi mencatat akun Admin, waktu, dan catatan perubahan.</p><div class="actions"><a href="/website" class="btn" target="_blank">Lihat website</a><a href="/admin/website" class="btn secondary">Kelola website</a></div></x-card>@endif
@endsection
